### ISSUE TITLE
Make Agave Spawn in World

### ISSUE THREAD

**Issue by boredhero** [boredhero/pv#11]
* The Agave plant needs to spawn in the overworld

1. Agave should spawn fully grown in all desert/mesa biomes.
2. Unlike the planted/farmed variant, it should ignore any requirements to be within 7 blocks of a water source to spawn.
3. It should spawn with about the same frequency as cactus or deadbush.

**Comment by matshou** [comment]
Perhaps this can be implemented by [Odyssey](https://github.com/yooksi/Odyssey/) so that PV remains more focused on beverages. Adding world generation would make the mod more bloated then it needs to be for its alpha-beta releases.

**Comment by boredhero** [comment]
> Perhaps this can be implemented by [Odyssey](https://github.com/yooksi/Odyssey/) so that PV remains more focused on beverages. Adding world generation would make the mod more bloated then it needs to be for its alpha-beta releases.

I mean I have no issue with that for now although by the time of late beta/release we will have our own village types and stuff that spawn in the world, but we don't need that just yet. I'm fine with Odyssey implementing it now I suppose. But what if they test the mods individually on their own before they add them to the pack? There would be no natural agave spawns then. Just a thought.

**Comment by matshou** [comment]
From what we talked about I thought we agreed that for the MMD-jam we will try to primarily develop PV in the context of supporting Odyssey. This is why you are working on tequila and the still, which should still work fine without Odyssey (they would just be un-craftable).
