### ISSUE TITLE
Unable to set localization for itemGroup.vinum

### ISSUE THREAD

**Issue by boredhero** [boredhero/pv#14]
I tried to add localization in en_us.json for the itemGroup.vinum tab as you normally would, but this isn't working for some reason. Any help is appreciated.

![2020-05-11_15-00](https://user-images.githubusercontent.com/12053148/81601490-f69cba80-9398-11ea-80f2-654656304595.png)

**Comment by matshou** [comment]
Does localization for other blocks/items works?

**Comment by boredhero** [comment]
> Does localization for other blocks/items works?

Yes. Strangely, however, it seems to have automajically fixed itself after I added the item localizations, so I'm closing this issue.
